import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect

PGQUEUER_TABLES = {
    "pgqueuer",
    "pgqueuer_log",
    "pgqueuer_schedules",
    "pgqueuer_statistics",
}


def test_migration_installs_the_queue_schema(database):
    """The `database` fixture already ran downgrade base then upgrade head."""
    with database() as db:
        tables = set(inspect(db.get_bind()).get_table_names())
    assert PGQUEUER_TABLES <= tables


def test_models_match_the_migration(database):
    """Also proves autogenerate ignores pgqueuer's tables rather than dropping them."""
    try:
        command.check(Config("alembic.ini"))
    except AutogenerateDiffsDetected as exc:
        pytest.fail(str(exc))
