"""initial schema

Revision ID: 772281984a76
Revises:
Create Date: 2026-08-21 16:47:38.388703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from research_mapper.engine import queue

# revision identifiers, used by Alembic.
revision: str = "772281984a76"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("issuer", "subject", name=op.f("uq_users_issuer_subject")),
    )
    op.create_table(
        "research_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("community", sa.String(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("head_version_number", sa.Integer(), nullable=False),
        sa.Column("workflow", sa.String(), nullable=False),
        sa.Column("workflow_version", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_research_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_sessions")),
    )
    op.create_index(
        op.f("ix_research_sessions_user_id"),
        "research_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "operations",
        sa.Column("research_session_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "awaiting_input",
                "complete",
                "failed",
                name="operationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("mutates_state", sa.Boolean(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_operations_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["research_session_id"],
            ["research_sessions.id"],
            name=op.f("fk_operations_research_session_id_research_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint(
            "research_session_id",
            "version_number",
            name=op.f("uq_operations_research_session_id_version_number"),
        ),
    )
    op.create_index(
        "ix_operations_session_created",
        "operations",
        ["research_session_id", "id"],
        unique=False,
    )
    op.create_index(
        "uq_operations_one_running_per_session",
        "operations",
        ["research_session_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "artifacts",
        sa.Column("research_session_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_artifacts_operation_id_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["research_session_id"],
            ["research_sessions.id"],
            name=op.f("fk_artifacts_research_session_id_research_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint(
            "research_session_id",
            "type",
            "version",
            name=op.f("uq_artifacts_research_session_id_type_version"),
        ),
    )
    op.create_index(
        op.f("ix_artifacts_operation_id"), "artifacts", ["operation_id"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("research_session_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "select_many",
                "select_one",
                "edit_list",
                "text",
                name="decisiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_decisions_operation_id_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["research_session_id"],
            ["research_sessions.id"],
            name=op.f("fk_decisions_research_session_id_research_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint(
            "operation_id", "key", name=op.f("uq_decisions_operation_id_key")
        ),
    )
    op.create_index(
        op.f("ix_decisions_research_session_id"),
        "decisions",
        ["research_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_pending_decisions",
        "decisions",
        ["research_session_id"],
        unique=False,
        postgresql_where=sa.text("answer IS NULL"),
    )
    # ### end Alembic commands ###
    op.execute(queue.install_ddl())


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(queue.uninstall_ddl())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_pending_decisions",
        table_name="decisions",
        postgresql_where=sa.text("answer IS NULL"),
    )
    op.drop_index(op.f("ix_decisions_research_session_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_artifacts_operation_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(
        "uq_operations_one_running_per_session",
        table_name="operations",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("ix_operations_session_created", table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_research_sessions_user_id"), table_name="research_sessions")
    op.drop_table("research_sessions")
    op.drop_table("users")
    # ### end Alembic commands ###
