"""evidence map session references

Revision ID: f7ab2b8af61b
Revises: 772281984a76
Create Date: 2026-08-26 09:06:48.994644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f7ab2b8af61b"
down_revision: Union[str, Sequence[str], None] = "772281984a76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_references",
        sa.Column("research_session_id", sa.UUID(), nullable=False),
        sa.Column("destiny_id", sa.UUID(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "gathered",
                "included",
                "excluded",
                "mapped",
                "failed",
                name="sessionreferencestage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("screening", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("coordinate", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_session_id"],
            ["research_sessions.id"],
            name=op.f("fk_session_references_research_session_id_research_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_references")),
        sa.UniqueConstraint(
            "research_session_id",
            "destiny_id",
            name=op.f("uq_session_references_research_session_id_destiny_id"),
        ),
    )
    op.create_index(
        "ix_session_references_stage",
        "session_references",
        ["research_session_id", "stage", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_references_stage", table_name="session_references")
    op.drop_table("session_references")
    # ### end Alembic commands ###
